-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 14:28:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema bodega
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bodega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bodega` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `mydb` ;
USE `bodega` ;

-- -----------------------------------------------------
-- Table `bodega`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bodega`.`responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega`.`responsable` (
  `id_responsable` INT(10) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(10) NOT NULL,
  `apellido` VARCHAR(10) NOT NULL,
  `telefono` INT(10) NOT NULL,
  `direccion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_responsable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bodega`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega`.`usuario` (
  `usuario` VARCHAR(20) NOT NULL DEFAULT 'admi',
  `contraseña` VARCHAR(20) NOT NULL,
  `id_usuario` INT(10) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bodega`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega`.`pedido` (
  `id_pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `id_responsable` INT(10) NOT NULL,
  `id_usuario` INT(10) NOT NULL,
  PRIMARY KEY (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `id_responsable_idx` ON `bodega`.`pedido` (`id_responsable` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `id_usuario_idx` ON `bodega`.`pedido` (`id_usuario` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bodega`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega`.`producto` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_categoria` INT(11) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `productocol` VARCHAR(45) NULL,
  `productocol1` VARCHAR(45) NULL,
  `productocol2` VARCHAR(45) NULL,
  `productocol3` VARCHAR(45) NULL,
  `productocol4` VARCHAR(45) NULL,
  `productocol5` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `id_categoria_idx` ON `bodega`.`producto` (`id_categoria` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bodega`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega`.`detalle` (
  `id_pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `id_producto` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `id_pedido_idx` ON `bodega`.`detalle` (`id_pedido` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `id_producto_idx` ON `bodega`.`detalle` (`id_producto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bodega`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega`.`stock` (
  `id_stock` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad_producto` INT(11) NOT NULL,
  PRIMARY KEY (`id_stock`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `bodega`.`detalle_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega`.`detalle_bodega` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_stock` INT(11) NOT NULL,
  `producto_entrantes` INT(11) NOT NULL,
  `productos_salientes` INT(11) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `id_producto_idx` ON `bodega`.`detalle_bodega` (`id_producto` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `id_stock_idx` ON `bodega`.`detalle_bodega` (`id_stock` ASC) VISIBLE;

SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
SHOW WARNINGS;
USE `mydb`;
select * from categorias;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
